blueprint:
  name: IKEA STYRBAR RGB – All-in-One (Z2M – FIX)
  description: >
    Versione stabile senza helper esterni.
    Palette IKEA, bianco caldo, luce notte,
    scena su pressione lunga, temperatura colore graduale.
  domain: automation

  input:
    mqtt_topic:
      name: Topic MQTT telecomando
      description: es. zigbee2mqtt/styrbar_sala/action
      selector:
        text:
    light:
      name: Lampada RGB
      selector:
        target:
          entity:
            domain: light

mode: restart

trigger:
  - platform: mqtt
    topic: !input mqtt_topic
    payload: on
  - platform: mqtt
    topic: !input mqtt_topic
    payload: off
  - platform: mqtt
    topic: !input mqtt_topic
    payload: brightness_move_up
  - platform: mqtt
    topic: !input mqtt_topic
    payload: brightness_move_down
  - platform: mqtt
    topic: !input mqtt_topic
    payload: arrow_right_click
  - platform: mqtt
    topic: !input mqtt_topic
    payload: arrow_left_click
  - platform: mqtt
    topic: !input mqtt_topic
    payload: arrow_right_hold
  - platform: mqtt
    topic: !input mqtt_topic
    payload: arrow_right_double
  - platform: mqtt
    topic: !input mqtt_topic
    payload: arrow_up_click
  - platform: mqtt
    topic: !input mqtt_topic
    payload: arrow_down_click

variables:
  palette:
    - [0, 100]     # Rosso
    - [30, 100]    # Arancio
    - [55, 100]    # Giallo IKEA
    - [120, 100]   # Verde
    - [200, 100]   # Azzurro
    - [240, 100]   # Blu
  warm_white: 370
  night:
    brightness: 10
    color_temp: 454

action:
  - variables:
      entity: "{{ expand(light.entity_id)[0].entity_id }}"
      hue: "{{ state_attr(entity,'hs_color')[0] | default(-1) }}"
      hues: "{{ palette | map('first') | list }}"
      idx: "{{ hues.index(hue) if hue in hues else -1 }}"

  - choose:

      # ON
      - conditions: "{{ trigger.payload == 'on' }}"
        sequence:
          - service: light.turn_on
            target: !input light

      # OFF
      - conditions: "{{ trigger.payload == 'off' }}"
        sequence:
          - service: light.turn_off
            target: !input light

      # DIMMER
      - conditions: "{{ trigger.payload == 'brightness_move_up' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness_step: 25

      - conditions: "{{ trigger.payload == 'brightness_move_down' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness_step: -25

      # TEMPERATURA COLORE GRADUALE
      - conditions: "{{ trigger.payload in ['arrow_up_click','arrow_down_click'] }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              color_temp: >
                {% set ct = state_attr(entity,'color_temp') | default(warm_white) %}
                {{ ct - 30 if trigger.payload == 'arrow_up_click' else ct + 30 }}

      # PALETTE CICLICA
      - conditions: "{{ trigger.payload == 'arrow_right_click' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              hs_color: "{{ palette[(idx + 1) % (palette | length)] }}"

      # RITORNO BIANCO CALDO
      - conditions: "{{ trigger.payload == 'arrow_left_click' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              color_temp: "{{ warm_white }}"

      # SCENA (HOLD)
      - conditions: "{{ trigger.payload == 'arrow_right_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness: 200
              color_temp: 300

      # LUCE NOTTE (DOUBLE)
      - conditions: "{{ trigger.payload == 'arrow_right_double' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data: "{{ night }}"
